# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Find your internship
email: fhs37229@fh-salzburg.ac.at
description: > # this means to ignore newlines until "baseurl:"
  jekyll page for potential internship candidates
baseurl: "internships" # the subpath of your site, e.g. /blog
url: "http://godfather27.github.io/" # the base hostname & protocol for your site
twitter_username: SebCHuber
github_username:  Godfather27
permalink: /:title

# Build settings
markdown: kramdown
